version: '2.1'

services:
  demo:
    image: demo
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DEMO_REDIS: redis
    ports:
      - 3000:3000
  redis:
    image: redis