version: '2.1'

services:
  demo:
    image: demo 
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      DEMO_REDIS: redis
    ports:
        - "3000:3000"
        - "2345:2345"
    security_opt:
        - "seccomp:unconfined"
    command: /go/bin/dlv debug --headless --log --listen=:2345 --api-version=2
    volumes:
        - .:/go/src/app
  redis:
    image: redis